version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: image-flow-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_flow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: image-flow-storage
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: image-flow-mq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: image-flow-cache
    ports:
      - "6379:6379"

  image-service:
    build:
      context: ./services
      dockerfile: apps/image-service/Dockerfile.dev
    container_name: image-flow-service
    ports:
      - "3000:3005"
    volumes:
      - ./services/apps/image-service:/usr/src/app
      - ./services/common:/usr/src/common
      - /usr/src/app/node_modules
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=image_flow
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_PUBLIC_URL=http://localhost:9000/images
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - minio
      - rabbitmq
      - redis
    command: sh -c "cd /usr/src/common && npm run build && cd /usr/src/app && npm run build && npm run start:dev"

  processor-service:
    build:
      context: ./services
      dockerfile: apps/processor-service/Dockerfile.dev
    ports:
      - "3010-3015:3015"
    volumes:
      - ./services/apps/processor-service:/usr/src/app
      - ./services/common:/usr/src/common
      - /usr/src/app/node_modules
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - IMAGE_SERVICE_URL=http://image-service:3005
    depends_on:
      - minio
      - rabbitmq
    command: sh -c "cd /usr/src/common && npm run build && cd /usr/src/app && npm run build && npm run start:dev"

  minio-init:
    image: minio/mc
    container_name: image-flow-storage-init
    depends_on:
      - minio
      - processor-service
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; do
        echo 'Waiting for MinIO...'
        sleep 2
      done;
      /usr/bin/mc mb --ignore-existing myminio/images;
      /usr/bin/mc anonymous set download myminio/images;
      until /usr/bin/mc admin config set myminio notify_webhook:1 endpoint='http://processor-service:3015/webhooks/minio' queue_limit='0'; do
        echo 'Waiting for processor-service webhook endpoint...'
        sleep 5
      done;
      /usr/bin/mc admin service restart myminio;
      sleep 5;
      until /usr/bin/mc event add myminio/images arn:minio:sqs::1:webhook --event put; do
        echo 'Waiting for event notification to be enabled...'
        sleep 2
      done;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
