apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: processor-service-scaler
  namespace: image-flow
spec:
  scaleTargetRef:
    name: processor-service
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod:  300
  triggers:
  - type: rabbitmq
    metadata:
      queueName: image_process_queue
      includeUnacked: "true"
      queueLength: "5"
      hostFromEnv: RABBITMQ_URL
