apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init-job
  namespace: image-flow
spec:
  template:
    spec:
      containers:
      - name: minio-init
        image: minio/mc
        command:
        - /bin/sh
        - -c
        - |
          until /usr/bin/mc alias set myminio http://minio-service:9000 minioadmin minioadmin; do
            echo 'Waiting for MinIO...'
            sleep 2
          done;
          /usr/bin/mc mb --ignore-existing myminio/images;
          /usr/bin/mc anonymous set download myminio/images;
          until /usr/bin/mc admin config set myminio notify_webhook:1 endpoint='http://processor-service:3015/webhooks/minio' queue_limit='0'; do
            echo 'Waiting for processor-service webhook endpoint...'
            sleep 5
          done;
          /usr/bin/mc admin service restart myminio;
          sleep 10;
          until /usr/bin/mc event add myminio/images arn:minio:sqs::1:webhook --event put; do
            echo 'Waiting for event notification to be enabled...'
            sleep 2
          done;
          echo 'MinIO initialization complete!';
      restartPolicy: OnFailure
  backoffLimit: 10
