FROM node:20-alpine

WORKDIR /usr/src/app

COPY common /usr/src/common
WORKDIR /usr/src/common
RUN npm install

WORKDIR /usr/src/app
COPY apps/image-service/package*.json ./
RUN npm install

COPY apps/image-service ./

CMD ["npm", "run", "start:dev"]
