FROM node:24-alpine

WORKDIR /usr/src/app

COPY common /usr/src/common
WORKDIR /usr/src/common
RUN npm install

WORKDIR /usr/src/app
COPY apps/processor-service/package*.json ./
RUN npm install

COPY apps/processor-service ./

CMD ["npm", "run", "start:dev"]
