FROM node:20-alpine

WORKDIR /usr/src/app

# Copy common first
COPY common /usr/src/common
WORKDIR /usr/src/common
RUN npm install

# Then copy service
WORKDIR /usr/src/app
COPY apps/processor-service/package*.json ./
RUN npm install

COPY apps/processor-service ./

CMD ["npm", "run", "start:dev"]
