{{- if .Capabilities.APIVersions.Has "keda.sh/v1alpha1" -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: processor-service-scaler
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: processor-service
  minReplicaCount: {{ .Values.processorService.minReplicas | default 1 }}
  maxReplicaCount: {{ .Values.processorService.maxReplicas | default 10 }}
  pollingInterval: 30
  cooldownPeriod:  300
  triggers:
  - type: rabbitmq
    metadata:
      queueName: image_process_queue
      includeUnacked: "true"
      queueLength: "5"
      hostFromEnv: RABBITMQ_URL
{{- end -}}
