apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.processorService.replicaCount }}
  selector:
    matchLabels:
      app: processor-service
  template:
    metadata:
      labels:
        app: processor-service
    spec:
      containers:
      - name: processor-service
        image: "{{ .Values.processorService.image.repository }}:{{ .Values.processorService.image.tag }}"
        imagePullPolicy: {{ .Values.processorService.image.pullPolicy }}
        ports:
        - containerPort: 3015
        envFrom:
        - configMapRef:
            name: image-flow-config
        - secretRef:
            name: image-flow-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: processor-service
  ports:
  - protocol: TCP
    port: 3015
    targetPort: 3015
