name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get_services:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set_matrix.outputs.services }}
    steps:
      - uses: actions/checkout@v4
      - id: set_matrix
        run: echo "services=$(ls -d services/apps/*/ | sed 's|services/apps/||;s/\/$//' | jq -c -R -s 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  test:
    needs: get_services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.get_services.outputs.services) }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: services/apps/${{ matrix.service }}/package-lock.json
      - name: Install dependencies
        working-directory: services/apps/${{ matrix.service }}
        run: npm ci
      - name: Lint
        working-directory: services/apps//${{ matrix.service }}
        run: npm run lint
      - name: Architecture tests
        working-directory: services/apps/${{ matrix.service }}
        run: npm run test:arch
      - name: Tests and coverage
        working-directory: services/apps/${{ matrix.service }}
        run: npm run test:cov
